name: macOS Build

on:
  push:
    branches:
      - main
      - unstable


permissions:
  contents: write 
  
env:
  QT_VERSION: 6.5.0
  ARCHIVE_NAME: OpenSprite-macOS-arm64-latest

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python (für aqtinstall)
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install aqtinstall
      run: |
        pip install aqtinstall

    - name: Install Qt
      run: |
        pip install aqtinstall
        aqt install-qt mac desktop $QT_VERSION clang_64 -O $HOME/Qt
    
    - name: Run qmake
      run: |
        $HOME/Qt/$QT_VERSION/macos/bin/qmake -Wall OpenSprite.pro

    - name: Build
      run: |
        make

    - name: Package app 
      run: |
        $HOME/Qt/6.5.0/macos/bin/macdeployqt ./build/Release/OpenSprite.app

    - name: Create DMG from .app
      run: |
        hdiutil create \
          -volname OpenSprite \
          -srcfolder ./build/Release/OpenSprite.app \
          -ov \
          -format UDZO \
          ${{ env.ARCHIVE_NAME }}.dmg

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: Automatic Build
        prerelease: true
        files: |
          OpenSprite-macOS-arm64-latest.dmg 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
