name: Windows C++ Qt Build

on:
  push:
    branches: [ "cicd" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download aqtinstall
      run: |
        Write-Host 'Downloading  aqtinstall ...'
        $src = 'https://github.com/miurahr/aqtinstall/releases/download/v3.1.6/aqt_x64_signed.exe'
        $target = 'C:\Windows\System32\aqt.exe'
        Invoke-WebRequest -Uri $src -OutFile $target

    - name: Install Qt
      run: |
        Write-Host 'Installing Qt ...'
        #aqt list-qt windows desktop --arch 6.2.0
        aqt install-qt windows desktop 6.2.0 win64_msvc2019_64 -O C:\Qt

    - name: List Dir 1
      run: Get-ChildItem C:\Qt

    - name: List Dir 2
      run: Get-ChildItem C:\Qt\6.2.0

    - name: Run qmake
      run: |
        Write-Host 'Running qmake ...'
        $Env:PATH = "C:\Qt\6.2.0;$($Env:PATH)"
        qmake --help
