name: Windows C++ Qt Build

on:
  push:
    branches:
      - main
      - cicd

env:
  QT_VERSION: 6.5.0
  AQT_PLATFORM: msvc2019_64

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MSVC
      uses: aminya/setup-cpp@v1
      with:
        compiler: msvc
        vcvarsall: true

    - name: Download aqtinstall
      run: |
        Write-Host 'Downloading  aqtinstall ...'
        $src = 'https://github.com/miurahr/aqtinstall/releases/download/v3.1.6/aqt_x64_signed.exe'
        $target = 'C:\Windows\System32\aqt.exe'
        Invoke-WebRequest -Uri $src -OutFile $target

    - name: Install Qt
      run: |
        Write-Host 'Installing Qt ...'
        #aqt list-qt windows desktop --arch $Env:QT_VERSION
        aqt install-qt windows desktop $Env:QT_VERSION "win64_${Env:AQT_PLATFORM}" -O C:\Qt

    - name: Run qmake
      run: |
        Write-Host 'Running qmake ...'
        $Env:PATH = "C:\Qt\${Env:QT_VERSION}\${Env:AQT_PLATFORM}\bin;${Env:PATH}"
        qmake --help
        Write-Host
        qmake -Wall -tp vc OpenSprite.pro

    - name: List qmake artifacts
      run: |
        Get-ChildItem . -Recurse

    - name: Build
      run: |
        msbuild OpenSprite.vcxproj -property:Configuration=Release

    - name: List artifacts
      run: |
        Get-ChildItem . -Recurse
        #Get-ChildItem C:\tmp -Recurse

    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: OpenSprite.exe
        path: build/release/OpenSprite.exe
